version: '2'
services:
   grpc:
      container_name: grpc
      build: ../grpc/
      expose:
         - "50054"

   localhost:
      container_name: localhost
      volumes_from:
         - grpc:ro
      build: .
      links:
         - grpc
      environment:
         - API_HOST=grpc
         - API_PORT=50054
      ports:
         - "8080:8080"